import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {once} from 'node:events';
import {Gateway} from '../src/llm/gateway.js';import {parseConfig} from '../src/llm/config.js';import {createGame} from '../src/domain/engine.js';import {observe} from '../src/domain/visibility.js';import {createRoster} from '../src/agents/personas.js';
async function server(reply:(body:any,headers:any,n:number)=>{status?:number;body?:any;location?:string}){let calls=0;const requests:any[]=[];const s=createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;const body=JSON.parse(text);requests.push({body,headers:req.headers});const out=reply(body,req.headers,++calls);res.writeHead(out.status||200,{'content-type':'application/json',...(out.location?{location:out.location}:{})});res.end(JSON.stringify(out.body??{choices:[{message:{content:'{"action":{"type":"wolfVote","targetSeat":null}}'}}]}));});s.listen(0,'127.0.0.1');await once(s,'listening');const url=`http://127.0.0.1:${(s.address() as any).port}`;return{url,requests,close:()=>new Promise<void>(resolve=>s.close(()=>resolve()))};}
function view(){const s=createGame({count:6,seed:42,humanRole:'wolf'});return observe(s,1);}
const cfg=(baseURL:string)=>({baseURL,apiKey:'fake-key-sentinel',model:'fixture',jsonMode:true,contextTokens:32000,maxRequests:300,maxTokens:200000});
test('configuration parsing never executes env text and rejects remote insecure URLs',()=>{const c=parseConfig('LLM_BASE_URL=http://localhost:11434/v1\nLLM_MODEL="local"\nLLM_API_KEY=$(never-execute)');assert.equal(c.apiKey,'$(never-execute)');assert.throws(()=>parseConfig('LLM_BASE_URL=http://example.com\nLLM_MODEL=x\nLLM_API_KEY=k'),/INSECURE_ENDPOINT/);});
test('model prompt is projected and key only appears in Authorization',async()=>{const fixture=await server(()=>({}));try{const g=new Gateway(cfg(fixture.url),{sleep:async()=>{}});const action=await g.decide(view(),createRoster(3).people[0]);assert.deepEqual(action,{type:'wolfVote',targetSeat:null});const request=fixture.requests[0];assert.equal(request.headers.authorization,'Bearer fake-key-sentinel');assert.ok(!JSON.stringify(request.body).includes('fake-key-sentinel'));assert.ok(!JSON.stringify(request.body).includes('deathReasons'));assert.equal(request.body.model,'fixture');}finally{await fixture.close();}});
test('empty and illegal output repaired once with legal view and then rejected',async()=>{const fixture=await server((_b,_h,n)=>({body:{choices:[{message:{content:n===1?'':'{"action":{"type":"wolfVote","targetSeat":99}}'}}]}}));try{const g=new Gateway(cfg(fixture.url));await assert.rejects(g.decide(view(),createRoster(3).people[0]),/INVALID_MODEL_OUTPUT/);assert.equal(fixture.requests.length,2);}finally{await fixture.close();}});
test('authentication failure is fatal and never blindly retried',async()=>{const fixture=await server(()=>({status:401,body:{error:'secret server detail'}}));try{const g=new Gateway(cfg(fixture.url));await assert.rejects(g.decide(view(),createRoster(3).people[0]),/AUTH_FAILED/);assert.equal(fixture.requests.length,1);}finally{await fixture.close();}});
test('transient errors retry boundedly and cross-origin redirect is blocked',async()=>{const fixture=await server((_b,_h,n)=>n<3?{status:503}:{});try{const g=new Gateway(cfg(fixture.url),{sleep:async()=>{}});await g.decide(view(),createRoster(3).people[0]);assert.equal(fixture.requests.length,3);}finally{await fixture.close();}const redirect=await server(()=>({status:302,location:'https://example.com'}));try{await assert.rejects(new Gateway(cfg(redirect.url)).decide(view(),createRoster(3).people[0]),/REDIRECT_BLOCKED/);}finally{await redirect.close();}});
test('aborted decisions and exhausted request budgets have no returned action',async()=>{const fixture=await server(()=>({}));try{const g=new Gateway({...cfg(fixture.url),maxRequests:1});await g.decide(view(),createRoster(3).people[0]);await assert.rejects(g.decide(view(),createRoster(3).people[0]),/BUDGET_EXCEEDED/);const ctrl=new AbortController();ctrl.abort();await assert.rejects(new Gateway(cfg(fixture.url)).decide(view(),createRoster(3).people[0],ctrl.signal));assert.equal(fixture.requests.length,1);}finally{await fixture.close();}});
